version: "3.7"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel-backend
    container_name: backend
    working_dir: /var/www/
    depends_on:
      - db
    tty: true
    ports:
      - 8000:8000
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: nextjs-frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - app-network
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge